---
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - dist
  - report
  - megalinter-reports
  - test-results
  - doc/standards
  - tests

FILTER_REGEX_EXCLUDE: '(^|/)(dist|test-results|doc/standards|tests)/'

IGNORE_GITIGNORED_FILES: true

DISABLE_LINTERS:
  [
    REPOSITORY_DEVSKIM,
    REPOSITORY_DUSTILOCK,
    SPELL_PROSELINT,
    COPYPASTE_JSCPD,
    BASH_EXEC,
    SPELL_LYCHEE,
  ]

VALIDATE_ALL_CODEBASE: false
PRINT_ALPACA: false
DISABLE_ERRORS: true
JAVASCRIPT_DEFAULT_STYLE: prettier
SARIF_REPORTER: true
REPOSITORY_GITLEAKS_ARGUMENTS: --no-git
REPOSITORY_TRUFFLEHOG_ARGUMENTS: "--exclude-paths=.trufflehogignore"
REPOSITORY_CHECKOV_ARGUMENTS: "--download-external-modules true"
REPOSITORY_GRYPE_ARGUMENTS: "--add-cpes-if-none"
CLEAR_REPORT_FOLDER: true
BASH_EXEC_FILTER_REGEX_EXCLUDE: "(libs?|tests?|examples?|vendor)"
BASH_SHFMT_ARGUMENTS: -i 2 -bn -ci -sr -kp
