#!/usr/bin/env bash
# shellcheck shell=bash
## @file tests/megalinter.bash
## @brief Exercises Repolinter through a real MegaLinter plugin load.
## @details
## Runs the descriptor named by `REPOLINTER_DESCRIPTOR`, defaulting to the
## maintained development descriptor, against deterministic local fixture
## repositories.  No fixture requires a network clone.
##
## MegaLinter requires local plugin descriptors to be hosted beneath a directory
## whose name contains `mega-linter-plugin-`.  The selected descriptor is copied
## byte-for-byte into a temporary staging directory with that naming convention
## before MegaLinter loads it.  The copy is compared with the selected descriptor
## before use so release integration still exercises the exact generated bytes.
##
## MegaLinter errors are explicitly enabled so Repolinter failures must affect the
## process exit status.

set -euo pipefail

readonly REPOLINTER_EX_NOINPUT=66
readonly REPOLINTER_EX_SOFTWARE=70
readonly MEGALINTER_IMAGE="${MEGALINTER_IMAGE:-ghcr.io/oxsecurity/megalinter-ci_light:v10.1.0}"
readonly REPOLINTER_DESCRIPTOR="${REPOLINTER_DESCRIPTOR:-mega-linter-plugin-repolinter/repolinter.megalinter-descriptor.yml}"
readonly PLUGIN_STAGE_DIR="test-results/mega-linter-plugin-repolinter-release"
readonly PLUGIN_STAGE_DESCRIPTOR="${PLUGIN_STAGE_DIR}/repolinter.megalinter-descriptor.yml"

## @fn stage_plugin_descriptor()
## @brief Stages the selected descriptor where MegaLinter accepts local plugins.
## @details
## Copies the selected descriptor into a test-results directory whose name
## satisfies MegaLinter's local plugin path convention, then verifies that the
## staged file is byte-identical to the selected descriptor.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## A diagnostic is written if the source descriptor is unreadable, staging fails,
## or the staged bytes differ from the source bytes.
##
## @returns Nothing is written to STDOUT.
## @retval 0 The descriptor was staged and verified.
## @retval 66 The selected descriptor is not readable.
## @retval 70 The staging directory, copy, or byte comparison failed.
stage_plugin_descriptor() {
  if [[ ! -r ${REPOLINTER_DESCRIPTOR} ]]; then
    printf 'Descriptor is not readable: %s\n' "${REPOLINTER_DESCRIPTOR}" >&2
    return "${REPOLINTER_EX_NOINPUT}"
  fi

  if ! mkdir -p -- "${PLUGIN_STAGE_DIR}"; then
    printf 'Unable to create plugin staging directory: %s\n' "${PLUGIN_STAGE_DIR}" >&2
    return "${REPOLINTER_EX_SOFTWARE}"
  fi

  if ! cp -- "${REPOLINTER_DESCRIPTOR}" "${PLUGIN_STAGE_DESCRIPTOR}"; then
    printf 'Unable to stage plugin descriptor: %s\n' "${REPOLINTER_DESCRIPTOR}" >&2
    return "${REPOLINTER_EX_SOFTWARE}"
  fi

  if ! cmp -s -- "${REPOLINTER_DESCRIPTOR}" "${PLUGIN_STAGE_DESCRIPTOR}"; then
    printf '%s\n' 'Staged plugin descriptor differs from the selected descriptor.' >&2
    return "${REPOLINTER_EX_SOFTWARE}"
  fi
}

## @fn run_megalinter()
## @brief Runs Repolinter through MegaLinter against one local fixture repository.
## @param target_dir Repository-relative fixture directory passed to Repolinter.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## MegaLinter writes its ordinary console report to STDOUT.
## @par STDERR
## MegaLinter and Docker diagnostics may be written to STDERR.
##
## @returns MegaLinter's console report.
## @retval 0 Repolinter accepted the selected fixture.
## @note Non-zero Docker, plugin-install, Repolinter, or MegaLinter statuses are
## propagated unchanged.
run_megalinter() {
  local target_dir=$1
  local plugin_uri="file://${PLUGIN_STAGE_DESCRIPTOR}"

  docker run \
    --rm \
    -v "${PWD}:/tmp/lint" \
    -w /tmp/lint \
    -e VALIDATE_ALL_CODEBASE=true \
    -e DISABLE_ERRORS=false \
    -e PRINT_ALPACA=false \
    -e SARIF_REPORTER=false \
    -e REPORT_OUTPUT_FOLDER=/tmp/megalinter-reports \
    -e "PLUGINS=[\"${plugin_uri}\"]" \
    -e ENABLE_LINTERS='["REPOSITORY_REPOLINTER"]' \
    -e "REPOSITORY_REPOLINTER_ARGUMENTS=${target_dir}" \
    "${MEGALINTER_IMAGE}"
}

stage_plugin_descriptor

if ! run_megalinter "tests/fixtures/good"; then
  printf '%s\n' 'Expected the compliant local fixture repository to pass.' >&2
  exit 1
fi

if run_megalinter "tests/fixtures/bad"; then
  printf '%s\n' 'Expected the noncompliant local fixture repository to fail.' >&2
  exit 1
fi
