---
name: MegaLinter

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  APPLY_FIXES: none

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/security@9949bad031045f366be2467e00e8371a7328a2e2 # v10.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ github.token }}

      - name: Archive MegaLinter reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            megalinter-reports/megalinter.log

      - name: Check for SARIF report
        id: sarif_file_exists
        if: always()
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: "megalinter-reports/megalinter-report.sarif"

      - name: Upload MegaLinter scan results
        if: steps.sarif_file_exists.outputs.files_exists == 'true'
        uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v3.29.5
        with:
          sarif_file: "megalinter-reports/megalinter-report.sarif"
